CREATE TABLE IF NOT EXISTS "User" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"telegram_id" INTEGER NOT NULL,
	"username" TEXT NOT NULL,
	"first_name" TEXT,
	"last_name" TEXT,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "Request" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"departure" TEXT NOT NULL,
	"departure_start_period" DATE NOT NULL,
	"return_end_period" DATE NOT NULL,
	"departure_options" JSON,
	"arrival" TEXT NOT NULL,
	"arrival_options" JSON,
	"duration" INTEGER NOT NULL,
	"adults" INTEGER NOT NULL,
	"round_trip" BOOLEAN NOT NULL,
	"created_at" DATE NOT NULL,
	"status" TEXT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Route" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"request_id" INTEGER NOT NULL,
	"departure" TEXT NOT NULL,
	"departure_date" DATE NOT NULL,
	"arrival" TEXT NOT NULL,
	"route_type" TEXT NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "Flight" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"route_id" INTEGER NOT NULL,
	"airline_code" TEXT NOT NULL,
	"departure_at" DATE NOT NULL,
	"arrival_at" DATE NOT NULL,
	"duration" INTEGER NOT NULL,
	"is_direct" BOOLEAN NOT NULL,
	"stop_count" INTEGER NOT NULL,
	"baggage_included" BOOLEAN NOT NULL,
	"baggage_type" TEXT,
	"baggage_weight" INTEGER,
	"hand_luggage_included" BOOLEAN NOT NULL,
	"seats_left" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "SearchSession" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"search_at" DATE NOT NULL,
	"site_aggregator" TEXT NOT NULL,
	"status" TEXT NOT NULL,
	"quality" JSON,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "FlightPrice" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"flight_id" INTEGER NOT NULL,
	"search_session_id" INTEGER NOT NULL,
	"found_at" DATE NOT NULL,
	"amount" INTEGER NOT NULL,
	"currency" TEXT NOT NULL,
	"cashback_amount" INTEGER,
	"cashback_currency" TEXT,
	PRIMARY KEY("id")
);



ALTER TABLE "Request"
ADD FOREIGN KEY("user_id") REFERENCES "User"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Route"
ADD FOREIGN KEY("request_id") REFERENCES "Request"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Flight"
ADD FOREIGN KEY("id") REFERENCES "Route"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "FlightPrice"
ADD FOREIGN KEY("flight_id") REFERENCES "Flight"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "FlightPrice"
ADD FOREIGN KEY("search_session_id") REFERENCES "SearchSession"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;